theme: minima
title: 'Data Organon | Gianluca Rossi''s Blog'
email: ganluca.rossi06@gmail.com
author: Gianluca Rossi

description: >- # this means to ignore newlines until "baseurl:"
  Experiences, ideas, discussions on everything related to
  data management platform in the Cloud. Although I work
  for Oracle, the views expressed on this blog are my own and do not necessarily
  reflect the views of Oracle.
baseurl: "data-organon/"
url: ""
github_username:   "gianlucarossi06"
google_analytics: "G-WP81WC62NJ"

